# Generated by Django 3.2.9 on 2021-12-14 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_sku', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('listing_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('variant_type', models.CharField(max_length=100)),
                ('category1', models.CharField(max_length=100)),
                ('category2', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('color_size', models.CharField(max_length=100)),
                ('custom_label0', models.CharField(max_length=100)),
                ('custom_label1', models.CharField(max_length=100)),
                ('custom_label2', models.CharField(max_length=100)),
                ('custom_label3', models.CharField(max_length=100)),
                ('custom_label4', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
