# Generated by Django 3.2.9 on 2022-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
