# Generated by Django 3.2.9 on 2022-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='company'),
        ),
    ]
