# Generated by Django 3.2.9 on 2022-02-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_company_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ref',
        ),
    ]
