version: "3.7"

services:
  python:
    container_name: opacity_api
    build:
      context: ..
      dockerfile: docker/Dockerfile      
    ports:
      - 127.0.0.1:$API_PORT:8080
    volumes:
      - $COMPANY_DATA:/repo/company_data
    environment:
    - DB_HOST=$DB_HOST
    - DB_NAME=$DB_NAME
    - DB_USER=$DB_USER
    - DB_PASSWORD=$DB_PASSWORD
    - DB_PORT=$DB_PORT
    - MEDIA_PATH=$MEDIA_PATH
  db:
    image: postgres
    volumes:
      - ./persistance:/var/lib/postgresql/data
      - ./media:/media_docker
    ports:
      - 127.0.0.1:5434:5432
    environment:
      - POSTGRES_USER=opacity
      - POSTGRES_PASSWORD=opacity
      - POSTGRES_DB=opacity

